### ISSUE TITLE
BUG: Error: Last key less than end of range

### ISSUE THREAD

**Issue by spentak** [nomic-io/merk#1]
```
<rejected> Error: Last key less than end of range
    at checkRange (/Users/devslopes/Desktop/blockchat/node_modules/lotion/node_modules/merk/src/verify.js:109:13)
```
Happens when making getState from lotion - guessing its similar to the other issue you just fixed for the head

To replicate: 

1. clone this repo: `https://github.com/devslopes/blockchat`

2. use node 8.2+ and then npm install

3. then `node bin/chat-client.js`

4. it will likely hang for a bit, and then give that error. If it does let you post messages, just a post a few and you will run into this

**Comment by mappum** [comment]
Closed since merk got reimplemented in Rust.
