### ISSUE TITLE
Suggested change for TreeOp::Put

### ISSUE THREAD

**Issue by davebryson** [nomic-io/merk#12]
Not a big deal, but one suggestion I have is to change`TreeOp::Put(&'a[u8])` to `TreeOp::Put(Vec<u8>)`.  Why?

1.  The consumer `Node.value` is already a `Vec<u8>`
2.  It simplifies TreeOp a bit (lifetime is not needed)
3.  It's easier to use `Put(Vec<u8>)` from external calls - (again simplifies lifetime stuff)

**Comment by mappum** [comment]
That was chosen for performance - I hate unneccessary clones. Would switching to `AsRef([u8])` solve this?

**Comment by mappum** [comment]
Ah but you're right that it's getting cloned into the node - maybe you're right and we can just change this 👌

**Comment by davebryson** [comment]
Made the change to try it out and see the perf difference.  It's in my [treeop branch](https://github.com/davebryson/merk/tree/treeop)

Bench results (just showing Put related ones):
test bench_put_insert_random:     `186,201,818 (&[u8])  --- 168,084,786    (Vec<u8>) ns/iter`
test bench_put_insert_sequential: `23,737,681 (&[u8])  --- 24,472,033   (Vec<u8>) ns/iter`
test bench_put_update_random:    `206,077,496 (&[u8])  --- 194,155,280 (Vec<u8>) ns/iter`
test bench_put_update_sequential `25,539,183 (&[u8])  --- 24,806,745   (Vec<u8>) ns/iter`

Performance wise they're pretty close. I'll settle for 23,809 random inserts per/sec 😄

Minimal touchpoints to make the change - :thumbsup: to the designer of this thing!

**Comment by mappum** [comment]
Closing this because #15 now uses `Vec<u8>`'s where we would have used `&[u8]`'s. In the future there might be a few places where we can optimize by using slices, but with a `AsRef<[u8]>` bound so that we can still accept `Vec<u8>`.
