### ISSUE TITLE
Object-splitting

### ISSUE THREAD

**Issue by mappum** [nomic-io/merk#3]
Currently, objects always take up exactly one tree node, so objects with many non-object properties become slow to parse/serialize/download. We could split large objects into multiple tree nodes based on e.g. serialized size or number of keys.

**Comment by siman** [comment]
What can you say about this structure of lotion.js state? Will nonces be loaded as one tree and in a case when we have 1 million of addresses in the `nonces` object all of them will be loaded once we try to read a nonce from one of those addresses inside of nonces?

```js
{
  nonces: {
    addr_1: 123,
    // ....
    addr_n: 456
  }
}
```

**Comment by mappum** [comment]
@siman That's up to your application, but if you're using [`coins`](https://github.com/mappum/coins) then then each nonce is in the relevant account object:
```js
{
  accounts: {
    'addr1': { nonce: 123, balance: 1000 },
    'addr2': { nonce: 456, balance: 1000 }
  }
}
```

If this issue is resolved it could be implemented in the way you suggest and not require loading all 1 million nonces even if it's one large map.

**Comment by mappum** [comment]
Closing since this now applies to the JS key/value logic which will live in another repo.
