### ISSUE TITLE
Benchmarks

### ISSUE THREAD

**Issue by mappum** [nomic-io/merk#5]
This module can be the biggest performance bottleneck in projects such as [`lotion`](https://github.com/keppel/lotion), so it will make sense to spend some time building benchmarks and optimizing against them.

**Comment by siman** [comment]
Hi, I'm also very interested in a performance of a state object of `lotion.js` in a case when a state object is too large. Let's say state object stores nonces for 1 million accounts – this is a common requirement for a blockchain project.

**Comment by mappum** [comment]
@siman That's definitely a focus of this module and I have been targeting performance for millions of accounts like you suggest. Everything should happen in roughly `O(log N)` so queries and updates should already be pretty efficient as long as the data is structured into many separate objects (but also even it isn't once #3 is implemented).

Last time I ran some rough benchmarks with ~1 million accounts on my Macbook, I was getting hundreds of updates per second, and tens or hundreds of thousands of queries per second (and I think this can be optimized much further once we need to).

**Comment by mappum** [comment]
With the Rust rewrite now we have lots of benchmarks and much higher performance, closing.
