### ISSUE TITLE
WebAssembly implementation

### ISSUE THREAD

**Issue by mappum** [nomic-io/merk#6]
This module can be easily optimized by porting performance-critical components (e.g. the tree operations) to a language that compiles to wasm (likely Rust). Also probably makes this module less prone to critical vulnerabilities since it's hard to reduce the complexity of this code and it pushes JS to its limits.

**Comment by mappum** [comment]
Closing since this was rewritten in Rust.

**Comment by okpatil4u** [comment]
Sorry @mappum, but does that mean that it could be compiled in WASM ?

**Comment by mappum** [comment]
Theoretically it could be, but RocksDB would need to be replaced by a different storage solution (e.g. IndexedDB).

**Comment by okpatil4u** [comment]
Yes, thank you !
