### ISSUE TITLE
Order of transactions in the tree

### ISSUE THREAD

**Issue by davebryson** [nomic-io/merk#8]
With [IAVL](https://github.com/tendermint/iavl) I believe it was (is) a best practice to sort transactions before committing them to the tree.  Is this true for `merk` as well?   Looking through the code it doesn't appear that it's doing so.   Great work by the way...

**Comment by mappum** [comment]
Interesting, any idea why? That seems unnecessary as long as the operations are produced in a deterministic order.

**Comment by davebryson** [comment]
I think determinism is the reason:  From the IAVL docs:

> On the other hand, while IAVL+ trees provide a deterministic merkle root hash, it depends on the order of transactions. In practice this shouldn't be a problem, since you can efficiently encode the tree structure when serializing the tree contents.

I know in the past when using IAVL you'd sort keys in the cache before committing to the tree.

**Comment by mappum** [comment]
Cool well in that case, I think the contract with the consumer of `merk` should be to make operations in a deterministic order. IMO it shouldn't be the data store's job to enforce that.

Although this should probably be outlined in the README to prevent confusion.

**Comment by mappum** [comment]
Closing since the Rust rewrite was made to sort the data by default, but also have a method which takes presorted data for higher performance.
